<a href="https://colab.research.google.com/github/Aphivich/DW/blob/master/hello_world.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("hello world")

hello world


### List

In [5]:
mylist = []
mylist.append("Aphivich")
mylist.append(200)
mylist

['Aphivich', 200]

How to count data


In [6]:
len(mylist)

2

## If Else PyThon


In [25]:
if mylist[1] > 250 :
  name = mylist[0]
  score = mylist[1]
  print(str(name)+" "+str(score))
else:
  print("Very Good!!")
  if score == 200 :
      print("Perfect")

Very Good!!
Perfect


In [48]:
summation = []
for i in range(0,10):
  summation.append(i)

for i in summation: #for-each loop
  print(str(i))

0
1
2
3
4
5
6
7
8
9


### NumPy

In [0]:
import numpy as np

Create array in numpy

In [53]:
l = [1, 2, 3, 4, 5]
np_array = np.array(l)
type(np_array)

numpy.ndarray

Create Martix in Array foramt

In [0]:
np_matrix = np.array([[1,2],[3,4],[5,6],[7,8]])

In [58]:
np_matrix

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
np.size(np_matrix,0)

4

In [63]:
np.size(np_matrix,1)

2

In [64]:
np_matrix.shape

(4, 2)

In [65]:
np_matrix.ndim

2

In [66]:
np_matrix.size

8

Create Matrix with Mix Data Type

In [0]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])

In [68]:
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

Access matrix element

In [69]:
np_mix_matrix[0,1]

'2'

Access all column of matrix


In [75]:
np_mix_matrix[:,0]

array(['one', 'three', 'five'], dtype='<U5')

In [88]:
np_mix_matrix[:,1]

array(['2', '4', '6'], dtype='<U5')

Access all row of matrix

In [86]:
np_mix_matrix[0]

array(['one', '2'], dtype='<U5')

Access element from row 0 to row 1

In [92]:
np_mix_matrix[0:2]

array([['one', '2'],
       ['three', '4']], dtype='<U5')

Type casting ndarraay object

In [93]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

matrix of zeros

In [94]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

matrix of one

In [95]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Eye matrix

In [102]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Empty matrix

In [101]:
np.empty([5,5])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

random matrix size

In [104]:
np.random.rand(5,5)

array([[0.94768882, 0.24878683, 0.60362998, 0.88904052, 0.71547425],
       [0.13071151, 0.68623149, 0.03870524, 0.88420615, 0.55207465],
       [0.4570859 , 0.0835639 , 0.90049968, 0.56689879, 0.13796385],
       [0.20815793, 0.51714104, 0.32037929, 0.5050443 , 0.28495313],
       [0.09936068, 0.49554909, 0.44417926, 0.20223399, 0.01725094]])

random size = 3,3 having value between 0 to 4

In [105]:
np.random.randint(5,size = (3,3))

array([[4, 3, 3],
       [4, 3, 4],
       [2, 4, 4]])

Ex1

In [119]:
np.random.rand(10,5)

array([[0.20117528, 0.62271298, 0.04468919, 0.28317467, 0.8192463 ],
       [0.44923455, 0.79624487, 0.20179808, 0.46045004, 0.23074645],
       [0.76558697, 0.26111628, 0.48446001, 0.14981585, 0.68645086],
       [0.63415126, 0.18742686, 0.28022091, 0.49351451, 0.61653518],
       [0.77876777, 0.3172737 , 0.82047095, 0.08799999, 0.4757783 ],
       [0.3630636 , 0.97214802, 0.6324926 , 0.29478193, 0.51576748],
       [0.75102167, 0.13762404, 0.00184557, 0.16249795, 0.12971033],
       [0.84491345, 0.98756904, 0.03289683, 0.61211701, 0.71294888],
       [0.55551565, 0.79534863, 0.46310796, 0.08893319, 0.7611082 ],
       [0.79800936, 0.8323361 , 0.73425805, 0.9186746 , 0.94568581]])

In [112]:
a = np.zeros([10,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [114]:
b = np.ones([10,5])
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [120]:
a[0,:] = b[0]
a

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [124]:
r = np.random.rand(10,5)
r

array([[0.69232782, 0.09625334, 0.62386258, 0.88821216, 0.18702414],
       [0.50710063, 0.46092749, 0.2556019 , 0.85953646, 0.81331178],
       [0.69460825, 0.14075815, 0.06905182, 0.51134743, 0.40428822],
       [0.48424476, 0.13808233, 0.13741659, 0.18776593, 0.417113  ],
       [0.40256614, 0.0905077 , 0.57085827, 0.43655387, 0.90009923],
       [0.1684119 , 0.70341535, 0.90850404, 0.9734023 , 0.61011681],
       [0.42016735, 0.27503436, 0.38538696, 0.80874958, 0.21426781],
       [0.38839963, 0.54063565, 0.88368773, 0.8436292 , 0.36364914],
       [0.26620846, 0.74856917, 0.649377  , 0.86080231, 0.47711098],
       [0.66892252, 0.2309707 , 0.9688926 , 0.77967691, 0.24134615]])

In [135]:
r[:,4] = a[:,4]
r[:,4] = b[:,4]
r

array([[0.69232782, 0.09625334, 0.62386258, 0.88821216, 1.        ],
       [0.50710063, 0.46092749, 0.2556019 , 0.85953646, 1.        ],
       [0.69460825, 0.14075815, 0.06905182, 0.51134743, 1.        ],
       [0.48424476, 0.13808233, 0.13741659, 0.18776593, 1.        ],
       [0.40256614, 0.0905077 , 0.57085827, 0.43655387, 1.        ],
       [0.1684119 , 0.70341535, 0.90850404, 0.9734023 , 1.        ],
       [0.42016735, 0.27503436, 0.38538696, 0.80874958, 1.        ],
       [0.38839963, 0.54063565, 0.88368773, 0.8436292 , 1.        ],
       [0.26620846, 0.74856917, 0.649377  , 0.86080231, 1.        ],
       [0.66892252, 0.2309707 , 0.9688926 , 0.77967691, 1.        ]])

In [0]:
c = np.random.choice(2,10)

# Ex1

In [143]:
r = np.random.rand(10,5)
c = np.random.choice(2,10)
r[:,4] = c
r

array([[0.0075366 , 0.12774903, 0.0370772 , 0.48085192, 0.        ],
       [0.39871644, 0.82809344, 0.24733118, 0.98305727, 0.        ],
       [0.8068671 , 0.17299953, 0.4464488 , 0.62508921, 1.        ],
       [0.45705111, 0.62820302, 0.23252191, 0.37035589, 1.        ],
       [0.97932138, 0.74146632, 0.28327692, 0.4409939 , 1.        ],
       [0.18695905, 0.4755083 , 0.45737367, 0.34346138, 0.        ],
       [0.02263497, 0.85905   , 0.19339202, 0.6250363 , 1.        ],
       [0.25449301, 0.28906759, 0.85076142, 0.55724362, 0.        ],
       [0.41432913, 0.68849236, 0.78013729, 0.06433449, 1.        ],
       [0.5232542 , 0.71627582, 0.05037011, 0.86853686, 0.        ]])

### Delete row

random (5,5) value 0 - 10


# Ex2

In [158]:
r = np.random.rand(10,5)
r

array([[0.59480488, 0.90497862, 0.76350253, 0.4237344 , 0.08724598],
       [0.54214373, 0.31522029, 0.551626  , 0.59843459, 0.20526664],
       [0.72755887, 0.6020519 , 0.95336412, 0.73577603, 0.99937315],
       [0.36964191, 0.40665343, 0.40158473, 0.11944838, 0.54828797],
       [0.47934651, 0.87952093, 0.59360516, 0.00695267, 0.67761933],
       [0.36470043, 0.67983229, 0.85942533, 0.21061462, 0.4314338 ],
       [0.67844943, 0.31966812, 0.17399061, 0.30735841, 0.92288789],
       [0.77591029, 0.40739716, 0.49003497, 0.43200187, 0.3318406 ],
       [0.65242159, 0.04423253, 0.05254993, 0.51260172, 0.56763415],
       [0.29240845, 0.01287134, 0.35925698, 0.91594215, 0.82436545]])

In [145]:
c = np.random.choice(3,10)
c

array([0, 1, 2, 2, 1, 1, 2, 1, 2, 1])

In [150]:
result = np.where(c == 2)
result

(array([2, 3, 6, 8]),)

In [161]:
r[2],r[3],r[6],r[8]

(array([0.72755887, 0.6020519 , 0.95336412, 0.73577603, 0.99937315]),
 array([0.36964191, 0.40665343, 0.40158473, 0.11944838, 0.54828797]),
 array([0.67844943, 0.31966812, 0.17399061, 0.30735841, 0.92288789]),
 array([0.65242159, 0.04423253, 0.05254993, 0.51260172, 0.56763415]))

In [194]:
r = np.random.rand(10,5)
c = np.random.choice(3,10)
q = np.where(c == 2)
r[q]

array([[0.60185801, 0.40387877, 0.12750881, 0.60588516, 0.37860377],
       [0.70441099, 0.18002445, 0.70960099, 0.80964742, 0.99965571],
       [0.92080861, 0.9877427 , 0.17738261, 0.27598383, 0.93685973]])

# Ex.2

In [193]:
r = np.random.rand(10,5)
c = np.random.choice(3,10)
q = np.where(c == 2)
r[q]

array([[0.55501367, 0.37603972, 0.39312931, 0.98486778, 0.42469752],
       [0.07972481, 0.24575266, 0.19887034, 0.87015222, 0.61130882],
       [0.37027627, 0.13233592, 0.08449213, 0.88462759, 0.94122185],
       [0.09671292, 0.75049054, 0.11254755, 0.58376124, 0.88683576]])